services:
  postgres:
    image: postgres:18-alpine
    container_name: upp_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: upp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d upp_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:8.2
    container_name: upp_mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: upp_mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: upp_server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/upp_db?schema=public
      - MONGO_URI=mongodb://mongo:mongo@mongo:27017/upp_mongo_db?authSource=admin
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started

volumes:
  postgres_data:
  mongo_data: